### ISSUE TITLE
FAR is being fed zero velocity in the middle of a launch?

### ISSUE THREAD

**Issue by aw1621107** [neuoy/KSPTrajectories#117]
FAR is spamming a bunch of these error messages in the logs during a launch:

```
[ERR 23:37:36.846] [FAR] NaN Prediction Section Error: Inputs: AtmDen: 0.7739819 Mach: 0 Re: 0 Kn: NaN skin: Infinity vel: (0.0, 0.0, 0.0)
```

The error messages result from FARAPI.CalculateVesselAeroForces being fed a velocity of 0. This really doesn't make sense, since the rocket is in the middle of a launch, and is definitely moving.

I tweaked the FAR code a bit to get a stack trace to determine how the error came about:

```
[ERR 23:37:36.846] [FAR]    at System.Environment.get_StackTrace()
   at FerramAerospaceResearch.FARAeroComponents.FARAeroSection.PredictionCalculateAeroForces(Single atmDensity, Single machNumber, Single reynoldsPerUnitLength, Single pseudoKnudsenNumber, Single skinFrictionDrag, Vector3 vel, ferram4.FARCenterQuery center)
   at FerramAerospaceResearch.FARAeroComponents.FARVesselAero.SimulateAeroProperties(Vector3 ByRef aeroForce, Vector3 ByRef aeroTorque, Vector3 velocityWorldVector, Double altitude)
   at FerramAerospaceResearch.FARAPI.InstanceCalcVesselAeroForces(.Vessel vessel, Vector3 ByRef aeroForce, Vector3 ByRef aeroTorque, Vector3 velocityWorldVector, Double altitude)
   at FerramAerospaceResearch.FARAPI.CalculateVesselAeroForces(.Vessel vessel, Vector3 ByRef aeroForce, Vector3 ByRef aeroTorque, Vector3 velocityWorldVector, Double altitude)
   at System.Reflection.MonoMethod.InternalInvoke(System.Object , System.Object[] , System.Exception ByRef )
   at System.Reflection.MonoMethod.Invoke(System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(System.Object obj, System.Object[] parameters)
   at Trajectories.FARModel.ComputeForces_Model(Vector3d airVelocity, Double altitude)
   at Trajectories.VesselAerodynamicModel.ComputeForces(Double altitude, Vector3d airVelocity, Vector3d vup, Double angleOfAttack)
   at Trajectories.AeroForceCache.ComputeCacheEntry(Int32 v, Int32 a, Int32 m)
   at Trajectories.AeroForceCache.GetCachedForce(Int32 v, Int32 a, Int32 m)
   at Trajectories.AeroForceCache.Sample2d(Int32 vFloor, Single vFrac, Int32 aFloor, Single aFrac, Int32 mFloor)
   at Trajectories.AeroForceCache.Sample3d(Int32 vFloor, Single vFrac, Int32 aFloor, Single aFrac, Int32 mFloor, Single mFrac)
   at Trajectories.AeroForceCache.GetForce(Double velocity, Double angleOfAttack, Double altitude)
   at Trajectories.VesselAerodynamicModel.GetForces(.CelestialBody body, Vector3d bodySpacePosition, Vector3d airVelocity, Double angleOfAttack)
   at Trajectories.Trajectory+<AddPatch>d__53.MoveNext()
   at Trajectories.Trajectory+<computeTrajectoryIncrement>d__47.MoveNext()
   at Trajectories.Trajectory.ComputeTrajectory(.Vessel vessel, Trajectories.DescentProfile profile)
   at Trajectories.Trajectory.Update()
```

Unfortunately, I'm a bit lost at this point, since I'm not sure exactly where Trajectories gets the velocity it feeds to FAR in the first place... Disabling the cache appears to cause the errors to go away, but this isn't an ideal solution.

This was an install with FAR, Trajectories, and RSS, as well as quite a few other mods which (hopefully) wouldn't affect things.

**Comment by aw1621107** [comment]
I guess one solution could be to just return 0 force if the vessel isn't moving, sort of like what #116 is doing if the vessel is packed, but I'm not sure whether there is something that needs to be addressed with the cache

**Comment by PiezPiedPy** [comment]
Not had time to look at this yet, @fat-lobyte knows this part of the code a lot better than me, maybe he can help sooner than I can but I know he is busy too.

**Comment by fat-lobyte** [comment]
Thanks, I will take a look at this - but I'm afraid not very soon. I am currently a bit busy.

This NaN seems very familiar, I recall reporting something very similar to the FAR bugtracker: ferram4/Ferram-Aerospace-Research#216.

BTW, and maybe I'm wrong, but the FAR-side code of the trajectory prediction is not working perticularly well. [This is the code](https://github.com/ferram4/Ferram-Aerospace-Research/blob/master/FerramAerospaceResearch/FARAPI.cs#L316) that gives us our numbers, and it doesn't look like there is even a way to specify vessel orientation. Last time i tried, prediction was way off.

I think getting FAR prediction to work properly may require quite a bit of work, and not just on the Trajectories side but also on the FAR side.

**Comment by neuoy** [comment]
Hi,

Indeed, we don't specify vessel orientation, it works the other way round: we specify air velocity relative to the current vessel orientation. But I don't think Ferram is actively testing and maintaining this API, so it might be broken.

**Comment by PiezPiedPy** [comment]
It appears that Trajectories is trying to send a zero velocity and altitude to the FARModel:ComputeForces_Model method, I'm thinking maybe the last iteration of the patches is getting through, not sure as I have not looked at that area of the code yet, just a guess.

 I'm assuming this bug could be any easy-ish fix to perform. (famous last words lol)

Anyway as a quick fix I have added into the FARModel:ComputeForces_Model method a check for Zero velocity, obviously not a proper fix but at least for the time being it will stop the spamming of the log file with the NaN errors.

**Comment by aw1621107** [comment]
Has this actually been fixed-fixed, not just log-spam-fix? I'd check myself, but my current computer can't really run KSP :(

**Comment by fat-lobyte** [comment]
> Has this actually been fixed-fixed, not just log-spam-fix? I'd check myself, but my current computer can't really run KSP :(

I'm not entirely sure, but we do have the commit ca5f18208c9b6164cbf48f975eb393e39e0295a7 which is supposed to fix this.

However, you should know that due to issue #125 , Trajectories will unfortunately not be very useful with FAR.
