### ISSUE TITLE
KSP 1.4.5: Moon SOI (RSS) and then the weirdness of spinning craft

### ISSUE THREAD

**Issue by Gordon-Dry** [neuoy/KSPTrajectories#155]
Well, reached SOI of the Moon, set a meneuver node to circularize and then the vessel started to spin and became faster and faster - until I disabled MechJeb orientation ...
(MechJeb dev808)

But no MechJeb issue here ...

A lot of these
```
Trajectories: *WARNING* Infinite loop in map view renderer. (InitMeshFromOrbit)
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Trajectories: *WARNING* Infinite loop in map view renderer. (InitMeshFromOrbit)
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Trajectories: *WARNING* Infinite loop in map view renderer. (InitMeshFromOrbit)
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Trajectories: *WARNING* Infinite loop in map view renderer. (InitMeshFromOrbit)
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
```
then this:```

getObtAtUT infinite UT on elliptical orbit UT: Infinity, returning NaN
   at System.Environment.get_StackTrace()
   at Orbit.getObtAtUT(Double UT)
   at Orbit.TrueAnomalyAtUT(Double UT)
   at Trajectories.MapOverlay.InitMeshFromOrbit(Vector3 bodyPosition, UnityEngine.Mesh mesh, .Orbit orbit, Double startTime, Double duration, Color color)
   at Trajectories.MapOverlay.RenderMesh()
   at Trajectories.MapOverlay+MapTrajectoryRenderer.OnPreRender()
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

ArithmeticException: NAN
  at System.Math.Sign (Double value) [0x00000] in <filename unknown>:0 
  at Orbit.solveEccentricAnomalyExtremeEcc (Double M, Double ecc, Int32 iterations) [0x00000] in <filename unknown>:0 
  at Orbit.solveEccentricAnomaly (Double M, Double ecc, Double maxError, Int32 maxIterations) [0x00000] in <filename unknown>:0 
  at Orbit.TrueAnomalyAtT (Double T) [0x00000] in <filename unknown>:0 
  at Orbit.TrueAnomalyAtUT (Double UT) [0x00000] in <filename unknown>:0 
  at Trajectories.MapOverlay.InitMeshFromOrbit (Vector3 bodyPosition, UnityEngine.Mesh mesh, .Orbit orbit, Double startTime, Double duration, Color color) [0x00000] in <filename unknown>:0 
  at Trajectories.MapOverlay.RenderMesh () [0x00000] in <filename unknown>:0 
  at Trajectories.MapOverlay+MapTrajectoryRenderer.OnPreRender () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)
```
then a lot of these
```
delta 0, target amt 50
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
```
Full log and stuff:
https://www.dropbox.com/s/j5tt7egl0mqg2d0/2018-10-18_1%20KSP.log%20and%20stuff.7z?dl=1

**Comment by fat-lobyte** [comment]
Of course, having these errors is not nice but I don't see what this has to do with rotating crafts. We don't apply forces to crafts.
